<a href="https://colab.research.google.com/github/LaResistancePL/First_repo/blob/main/ZD2_PawelCiosmak.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TASK 1 Solving matrices
1st one

In [1]:
import numpy as np

# matrix A
matrix_a = np.array([[-1, 1, 2],
              [0, -1, -3],
              [4, -3, 2]])

In [2]:
# vector b
vector_b = np.array([1, -4, 7])
# inverse of matrix A
matrix_a_inv = np.linalg.inv(matrix_a)
# x by multiplying A_inv by vector b
x = np.dot(matrix_a_inv, vector_b)

In [5]:
# Round the values & printing results
x_rounded = np.round(x).astype(int)
print("x1 =", x_rounded[0])
print("x2 =", x_rounded[1])
print("x3 =", x_rounded[2])

x1 = 2
x2 = 1
x3 = 1


TASK 1 Solving matrices
2nd one

In [6]:
# matrix B
matrix_b = np.array([[3, -1, 0],
              [2, -2, 4],
              [5, -6, 2]])

In [7]:
# vector c
vector_c = np.array([4, 8, 13])

# inverse of martrix B
matrix_b_inv = np.linalg.inv(matrix_b)

# x by multiplying matrix B by vector c
x = np.dot(matrix_b_inv, vector_c)

In [8]:
#Round the values & printing results
x_rounded = np.round(x).astype(int)
print("x1 =", x_rounded[0])
print("x2 =", x_rounded[1])
print("x3 =", x_rounded[2])

x1 = 1
x2 = -1
x3 = 1


Task 2. Solving a problem with a graphical description

In [24]:
# tree = x , apple = y , banana = z
# matrix C
matrix_c = np.array(
 [[3, 0, 0],
 [0, 1, 2],
 [1, 2, 0]]
 )

In [25]:
# vector d
vector_d = np.array([60, 23, 30])
# results for x,y,z
result_vector = np.linalg.solve(matrix_c, vector_d)

In [26]:
# checking and printing
print(f"A = {matrix_c}")
print(vector_d)
print(np.linalg.solve(matrix_c, vector_d))
print("tree =", result_vector[0])
print("apple =", result_vector[1])
print("banna =", result_vector[2])

A = [[3 0 0]
 [0 1 2]
 [1 2 0]]
[60 23 30]
[20.  5.  9.]
tree = 20.0
apple = 5.0
banna = 9.0


In [27]:
# final result for x + y + z
final_result = result_vector[0] + result_vector[1] + result_vector[2]
print(final_result)

34.0


TASK 3 Solving a problem with a textual condition

Three types of specialists worked on the project: designers, developers, and testers. We know the number of hours spent at each stage of development and the amount of money allocated for each stage as cost price.
The entire development was divided into 3 stages by the manager: creating the design, developing the software, and final testing.
The first stage took the designer 20 hours and the developers 3 hours; this stage was allocated a budget of 800 dollars. The second stage took the designers 8 hours, developers 28 hours, and testers 4 hours and was allocated 900 dollars. In the final stage, designers worked for 4 hours, developers for 12 hours, and testers for 32 hours. The budget was 600 dollars.
Find the cost per hour for each specialist by solving a system of linear equations, based on the data from the development stages.

In [28]:
# Cost of one hour of work: d = designers, p = programmers (developers), t = testers
# matrix D
matrix_d = np.array([[20, 3, 0],
              [8, 28, 4],
              [4, 12, 32]])

In [29]:
# vector e
vector_e = np.array([800, 900, 600])

In [31]:
# solving and printing results
vector_f = np.linalg.solve(matrix_d, vector_e)

print("Cost of one hour of designers work:", vector_f[0])
print("Cost of one hour of developers work:", vector_f[1])
print("Cost of one hour of testers work:", vector_f[2])

Cost of one hour of designers work: 36.89655172413793
Cost of one hour of developers work: 20.689655172413794
Cost of one hour of testers work: 6.379310344827586
